// src/components/BraillePanel.jsx

// 🔹 Braille mapping
const brailleMap = {
  a:"⠁",b:"⠃",c:"⠉",d:"⠙",e:"⠑",f:"⠋",g:"⠛",h:"⠓",
  i:"⠊",j:"⠚",k:"⠅",l:"⠇",m:"⠍",n:"⠝",o:"⠕",p:"⠏",
  q:"⠟",r:"⠗",s:"⠎",t:"⠞",u:"⠥",v:"⠧",w:"⠺",x:"⠭",
  y:"⠽",z:"⠵",
  " ":" ",
  "\n": "\n"
};

// 🔹 Convert text → braille
const textToBraille = (text = "") => {
  return text
    .toLowerCase()
    .split("")
    .map(c => brailleMap[c] || "")
    .join("");
};

const BraillePanel = ({ capture }) => {
  if (!capture) {
    return (
      <div className="flex items-center justify-center h-48 border border-dashed border-gray-700 rounded-xl">
        <p className="text-gray-500 text-sm">No capture selected</p>
      </div>
    )
  }

  // Generate braille from frontend if not in DB
  const braille =
    capture.braille_unicode ||
    textToBraille(capture.raw_text || "");

  // ── Download .brf using frontend-generated braille ──
  const downloadBrf = () => {
    const content = braille || capture.raw_text || "No content"
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `brixel_${capture.id?.slice(0, 8) || "export"}.brf`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Download .txt raw text ──
  const downloadText = () => {
    const content = capture.raw_text || "No content"
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `brixel_text_${capture.id?.slice(0, 8) || "export"}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Print with real braille dots ──
  const handlePrint = () => {
    const printWindow = window.open("", "_blank")
    printWindow.document.write(`
      <html>
        <head>
          <title>Brixel Braille Export</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: monospace; padding: 48px; background: #fff; color: #000; }
            .header { border-bottom: 2px solid #000; padding-bottom: 16px; margin-bottom: 24px; }
            .header h1 { font-size: 22px; font-weight: bold; }
            .header p  { font-size: 12px; color: #444; margin-top: 6px; }
            .meta-row  { display: flex; gap: 24px; font-size: 11px; color: #666; margin-bottom: 28px; }
            .section   { margin-bottom: 28px; }
            .section h2 {
              font-size: 11px; font-weight: bold;
              text-transform: uppercase; letter-spacing: 1.5px;
              color: #555; margin-bottom: 10px;
            }
            .text-box {
              border: 1px solid #ddd; border-radius: 6px;
              padding: 16px; font-size: 15px; line-height: 1.7;
            }
            .braille-box {
              border: 1px solid #ddd; border-radius: 6px;
              padding: 16px; font-size: 32px;
              letter-spacing: 6px; line-height: 2.4;
              word-break: break-all; white-space: pre-wrap;
            }
            .footer {
              margin-top: 40px; border-top: 1px solid #ddd;
              padding-top: 12px; font-size: 10px;
              color: #999; text-align: center;
            }
            @media print { body { padding: 24px; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Brixel — Whiteboard Capture</h1>
            <p>AI Classroom Assistant for Visually Impaired Students</p>
          </div>

          <div class="meta-row">
            <span>📅 ${new Date(capture.captured_at).toLocaleString()}</span>
            <span>📚 Subject: ${capture.subject_guess || "Unknown"}</span>
            <span>🎯 Confidence: ${capture.confidence != null ? Math.round(capture.confidence * 100) + "%" : "N/A"}</span>
          </div>

          <div class="section">
            <h2>Extracted Text</h2>
            <div class="text-box">${capture.raw_text || "No text available"}</div>
          </div>

          <div class="section">
            <h2>Braille Output</h2>
            <div class="braille-box">${braille || "⠀"}</div>
          </div>

          <div class="footer">
            Generated by Brixel (VisionBoard) • ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => printWindow.print(), 300)
  }

  return (
    <div className="bg-[#0f172a] border border-gray-800 rounded-xl p-6 space-y-6">

      {/* 🔹 Extracted Text */}
      <div>
        <span className="text-xs font-semibold text-teal-400 uppercase tracking-widest">
          Extracted Text
        </span>
        <p className="mt-3 text-white text-base leading-relaxed whitespace-pre-wrap">
          {capture.raw_text || "No text extracted"}
        </p>
      </div>

      {/* 🔹 Braille Output */}
      <div className="border-t border-gray-800 pt-6">
        <span className="text-xs font-semibold text-teal-400 uppercase tracking-widest">
          Braille Unicode
        </span>
        <p className="mt-3 text-white text-2xl leading-loose font-mono tracking-widest whitespace-pre-wrap">
          {braille || "⠀"}
        </p>
      </div>

      {/* 🔹 Assignment tag */}
      {capture.is_assignment && (
        <div className="bg-amber-900/30 border border-amber-700/50 rounded-lg px-4 py-3">
          <p className="text-amber-400 text-sm font-semibold">
            Assignment detected on this capture
          </p>
        </div>
      )}

      {/* 🔹 Metadata */}
      <div className="flex gap-3 text-xs text-gray-500">
        <span>Subject: {capture.subject_guess || "Unknown"}</span>
        <span>•</span>
        <span>
          Confidence: {capture.confidence
            ? `${Math.round(capture.confidence * 100)}%`
            : "N/A"}
        </span>
        <span>•</span>
        <span>{new Date(capture.captured_at).toLocaleTimeString()}</span>
      </div>

      {/* 🔹 Action Buttons */}
      <div className="border-t border-gray-800 pt-5 flex flex-wrap gap-3">
        <button
          onClick={downloadBrf}
          className="flex items-center gap-2 bg-teal-600 hover:bg-teal-500
                     text-white text-sm font-semibold px-5 py-2.5 rounded-lg
                     transition-colors duration-200"
        >
          ⬇ Download .brf
        </button>

        <button
          onClick={downloadText}
          className="flex items-center gap-2 bg-[#1e293b] hover:bg-[#334155]
                     text-white text-sm font-semibold px-5 py-2.5 rounded-lg
                     border border-gray-700 transition-colors duration-200"
        >
          ⬇ Download .txt
        </button>

        <button
          onClick={handlePrint}
          className="flex items-center gap-2 bg-[#1e293b] hover:bg-[#334155]
                     text-white text-sm font-semibold px-5 py-2.5 rounded-lg
                     border border-gray-700 transition-colors duration-200"
        >
          🖨 Print Braille
        </button>
      </div>

    </div>
  )
}

export default BraillePanel
