const PrintExport = ({ capture }) => {
  if (!capture) return null

  // ── Generate BRF content from whatever data is available ──
  const buildBrfContent = () => {
    // Use braille_brf if it exists, otherwise fall back to braille_unicode or raw_text
    if (capture.braille_brf) return capture.braille_brf
    if (capture.braille_unicode) return capture.braille_unicode
    if (capture.raw_text) return capture.raw_text
    return 'No content available'
  }

  const downloadBrf = () => {
    const content = buildBrfContent()
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `brixel_${capture.id.slice(0, 8)}.brf`
    a.click()
    URL.revokeObjectURL(url)
  }

  const downloadText = () => {
    if (!capture.raw_text) return
    const blob = new Blob([capture.raw_text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `brixel_text_${capture.id.slice(0, 8)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>Brixel Braille Export</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
              font-family: monospace; 
              padding: 48px; 
              background: #fff;
              color: #000;
            }
            .header {
              border-bottom: 2px solid #000;
              padding-bottom: 16px;
              margin-bottom: 24px;
            }
            .header h1 { font-size: 22px; font-weight: bold; }
            .header p  { font-size: 12px; color: #444; margin-top: 6px; }
            .section { margin-bottom: 28px; }
            .section h2 { 
              font-size: 11px; 
              font-weight: bold; 
              text-transform: uppercase; 
              letter-spacing: 1.5px;
              color: #555;
              margin-bottom: 10px; 
            }
            .text-box {
              border: 1px solid #ddd;
              border-radius: 6px;
              padding: 16px;
              font-size: 15px;
              line-height: 1.7;
            }
            .braille-box {
              border: 1px solid #ddd;
              border-radius: 6px;
              padding: 16px;
              font-size: 30px;
              letter-spacing: 6px;
              line-height: 2.2;
              word-break: break-all;
            }
            .meta-row {
              display: flex;
              gap: 24px;
              font-size: 11px;
              color: #666;
              margin-bottom: 28px;
            }
            .footer {
              margin-top: 40px;
              border-top: 1px solid #ddd;
              padding-top: 12px;
              font-size: 10px;
              color: #999;
              text-align: center;
            }
            @media print {
              body { padding: 24px; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Brixel — Whiteboard Capture</h1>
            <p>AI Classroom Assistant for Visually Impaired Students</p>
          </div>

          <div class="meta-row">
            <span>📅 ${new Date(capture.captured_at).toLocaleString()}</span>
            <span>📚 Subject: ${capture.subject_guess || 'Unknown'}</span>
            <span>🎯 Confidence: ${capture.confidence != null ? Math.round(capture.confidence * 100) + '%' : 'N/A'}</span>
          </div>

          <div class="section">
            <h2>Extracted Text</h2>
            <div class="text-box">${capture.raw_text || 'No text available'}</div>
          </div>

          <div class="section">
            <h2>Braille Output</h2>
            <div class="braille-box">${capture.braille_unicode || buildBrfContent()}</div>
          </div>

          <div class="footer">
            Generated by Brixel (VisionBoard) • ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => printWindow.print(), 300)
  }

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={downloadBrf}
        className="flex items-center gap-2 bg-teal-600 hover:bg-teal-500 
                   text-white text-sm font-semibold px-5 py-2.5 rounded-lg 
                   transition-colors duration-200"
      >
        ⬇ Download .brf
      </button>

      <button
        onClick={downloadText}
        className="flex items-center gap-2 bg-[#1e293b] hover:bg-[#334155] 
                   text-white text-sm font-semibold px-5 py-2.5 rounded-lg 
                   border border-gray-700 transition-colors duration-200"
      >
        ⬇ Download .txt
      </button>

      <button
        onClick={handlePrint}
        className="flex items-center gap-2 bg-[#1e293b] hover:bg-[#334155] 
                   text-white text-sm font-semibold px-5 py-2.5 rounded-lg 
                   border border-gray-700 transition-colors duration-200"
      >
        🖨 Print Braille
      </button>
    </div>
  )
}

export default PrintExport
